backend:
  name: github
  repo: turinglabsorg/netlifycms-vue-starter
  branch: master
media_folder: "public/uploads"
collections:
  - name: "translations" # Used in routes, e.g., /admin/collections/blog
    label: "Translations" # Used in the UI
    folder: "public/contents/translations" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Global", name: "global", widget: "string"}
      - {label: "English", name: "en", widget: "string"}
      - {label: "Italian", name: "it", widget: "string"}